# Generated by Django 4.1.6 on 2023-02-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.IntegerField(default=None),
        ),
    ]
