# Generated by Django 4.1.6 on 2023-02-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='minutes',
            field=models.IntegerField(null=True),
        ),
    ]
