# Generated by Django 4.1.6 on 2023-02-21 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_time_end_alter_time_minutes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Time',
        ),
    ]
