# Generated by Django 4.1.6 on 2023-02-22 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('times', '0003_alter_time_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='time',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
