version: "3.9"
services:
  web:
    build: ..
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      SECRET_KEY: ${SECRET_KEY}
      REDIS_HOST: redis
    command: python manage.py test
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_HOST: ${DATABASE_HOST}

  redis:
    image: redis:latest

# docker-compose -f docker/docker-compose.test.yml up --abort-on-container-exit --exit-code-from web